app:
  env: local
  httpaddr: 127.0.0.1
  httpport: 3001

db:
  driver: mysql
  host: 172.20.7.101
  port: 3306
  name: golang_rest
  user: root
  password: root

jwt:
  secret: mysecretkey


qm: 
  apiurl: 
  ownercode: 
  customerid: 
  secret: 
  appkey: 
  signmethod: md5
  format: xml
  version: 2.0